# Generated by Django 5.2 on 2025-05-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
