# Generated by Django 5.2.1 on 2025-05-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='icon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
