# Generated by Django 5.2.1 on 2025-05-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_icon_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='icon',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
