# Generated by Django 5.2.1 on 2025-05-24 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_document_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allowed_users',
            field=models.ManyToManyField(null=True, related_name='allowed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
