# Generated by Django 5.2.1 on 2025-05-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_document_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
