# Generated by Django 5.2.1 on 2025-05-24 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_document_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
