# Generated by Django 5.2.1 on 2025-05-25 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_document_allowed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='creator',
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
