# Generated by Django 5.2.1 on 2025-05-25 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_document_creator_document_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='allowed_users',
            field=models.ManyToManyField(related_name='documents_with_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
