# Generated by Django 5.2.1 on 2025-05-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_document_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
